### ISSUE TITLE
How should we manage Text/Paragraph in Kaizen? 

### ISSUE THREAD

**Issue by ActuallyACat** [cultureamp/kaizen-design-system#1037]
Semantically, Paragraph is confusing as it's not clear that this is also intended to be used for inline-text. 

We have deprecated Text - should we reclaim it?

**Comment by mbylstra** [comment]
Yes, I think it'd be great to reclaim the `Text` name.

We'd have to completely remove (not just add deprecation warnings) to the legacy Text component (https://github.com/cultureamp/kaizen-design-system/tree/master/packages/component-library/components/Text). 

It's also confusing have the Text component exist because people might be still using it (if they don't notice the deprecation warnings)

Perhaps this could be code moddable breaking change? Once we've removed Elm from Kaizen, then writing JS/TS/Flow codemods becomes a lot more feasible (there's no AST based codemod tool available for Elm, just an unreleased one in a private repo somewhere). I remember we ran into difficulties distinguishing between Flow and Typescript, but there might be a path forward.

The old `Text` module is used in an enormous number of places from memory - having to manually upgrade old code sounds really problematic (could just end up pinning codebases to an old version of @kaizen/component-library because it's too much work)

**Comment by mbylstra** [comment]
Another issue is that the old component has the baseline shift (I believe), but the Paragraph component doesn't. Perhaps a way to solve that is to include a wrapper shim component that provides the baseline offset (so we don't get visually breaking changes). The codemod would add this... OR... it could be an optional thing. Eg: if you're willing to do the QA, just use the codemod without the baseline shift wrapper, and if things still look fine, you are good to go.

**Comment by lloydstubber** [comment]
Moved into discussion [here](https://github.com/cultureamp/kaizen-design-system/discussions/1872)
