### ISSUE TITLE
If a select dropdown exceeds the height of the modal, what is the best practice?

### ISSUE THREAD

**Issue by mindycultureamp** [cultureamp/kaizen-design-system#147]
If a select sits within a Modal, and the dropdown contains many select options, what is the best practice? 
- Show the dropdown above the bottom bar of the modal?
- Show the dropdown within the confines of the modal, but make it scrollable?

**Comment by didoesdigital** [comment]
Clipping a Select's dropdown part obscures the options, making it more difficult to access. The user would then need to either scroll within a very limited vertical space or close the Select, scroll the Modal further, and open it again. If the dropdown part fully falls beneath the bottom bar, the user might not be able to see or realise there's a dropdown part at all. For these reasons, I believe the **Select's dropdown should appear above the bottom bar of the modal**. The dropdown options menu of native `select` elements will also appear above the bottom bar by default, so it would be nice to match this behavior.

**Growing modals**: If an Input/Edit Modal has lots of content, by default the modal will grow taller and the user can scroll the modal, as shown in the React [Modal story: Test - scrolling modal and scrolling content](https://cultureamp.design/storybook-static/?path=/story/modal--test-scrolling-modal-and-scrolling-content).

**Scrollable modal body**: Someone using the Modal component might choose to add `overflow-y: auto;` via the `.scrollable` class to the modal body so that any overflowing content will cause a scrollbar to appear in the body section instead of the modal growing taller. With a scrollable modal body, the Select's dropdown part would be cropped by the modal bottom bar, regardless of the intention of the Select while the Select dropdown part uses `absolute` positioning (maybe we could change that to `fixed` somehow?). 

**Lots of modal content**: We would likely only want a scrollable modal body if we expected a lot of modal content causing the modal to grow and want to keep the modal focused centrally in the screen with easy access to a persistent modal confirmation button. This would likely be less responsive and could make it impossible to reach the bottom of a modal on short screens. In general, too much modal content suggests that a modal might not be the best approach.

### Recommendations

- **We update Select documentation** to note that the Select dropdown options menu should appear over the top of other content without clipping so people can see and access it.
- **We update Modal documentation** to discourage scrollable modal bodies, including the a list of trade-offs to consider: clipping Select dropdowns, responsiveness on small screens, and design smell that modal might not be the best approach.

**Comment by lindsey-collins** [comment]
I wouldn't say that this is best practice necessarily, but I've also seen a pattern where the dropdown changes to a dropup when it's constrained by things such as the edge of a modal, the bottom of the page, etc. I'm not fond of this because I find it confusing if I don't know whether something is a dropdown or a dropup, but I've seen it a bit so thought I'd throw that into the ring.

**Comment by mindycultureamp** [comment]
Thanks Di! I think the recommendation makes sense 👍 
And I like the call out here that if the modal has lots of content, to reconsider using a modal.

**Comment by lijuenc** [comment]
Those recommendations make sense to me too.

> We update Modal documentation to discourage scrollable modal bodies, including the a list of trade-offs to consider: clipping Select dropdowns, responsiveness on small screens, and design smell that modal might not be the best approach.

Yeah, scrollable modal bodies exist more as a fallback for when content is unintentionally long - like a full sized modal on desktop shrinking to fit in a small viewport. So it's good that that will be explicitly mentioned in the trade-offs.
