### ISSUE TITLE
the yeoman generator (yo @kaizen/create:draft) is throwing errors

### ISSUE THREAD

**Issue by mbylstra** [cultureamp/kaizen-design-system#1838]
I see this error when I run `yo @kaizen/create:draft` after installing latest `yo` and `yarn @kaizen/generator-create@latest`:

```
yo @kaizen/create:draft
Error @kaizen/create:draft

Class constructor Generator cannot be invoked without 'new'
```

A few weeks ago @lloydstubber got this error:

```
-> yo @kaizen/create:draft

   Error @kaizen/create:draft
   Unexpected token ':'
```

**Comment by mbylstra** [comment]
I've made a start in https://github.com/cultureamp/kaizen-design-system/pull/1837

**Comment by ActuallyACat** [comment]
I'm finding this workflow with Yeoman really clunky - updating the generator, getting it publish (although that part happens automatically) and _then_ getting consumers to update their Yo generator globally is not an ideal workflow. Something like this might be preferable in the long term, since we can keep the generator local to this repo and not need people to grab the latest version of the generator: https://github.com/jondot/hygen

**Comment by mbylstra** [comment]
Yeah, I agree. It's really hard to debug too. There's so much magic with how Yeoman links up with the published generators. I tried this: https://yeoman.io/authoring/debugging.html, but npx doesn't even support the `--node-arg=` flag any more, and the environment variable option didn't seem to do anything. I really got to my wit's end trying to debug this - seems like it might be easier to just start again with a different library/framework and just replace the guts. It'd be better if it was just a standalone tool that was easier to install and debug - Hygen looks good.
