### ISSUE TITLE
Menu component does not gracefully handle menus taller than available space

### ISSUE THREAD

**Issue by makenosound** [cultureamp/kaizen-design-system#628]
![image](https://user-images.githubusercontent.com/4353/86857847-bf315c80-c102-11ea-8924-c147f30831aa.png)

I’ve started using the draft-menu and ran into a funny positioning issue. I think it’s because it’s (currently through bad data) very tall, and the menu goes “Hey, too tall to render below” and so it renders it above but doesn’t check that there’s room above. I think in this situation we’d ideally want it to render below, but clip the content and allow it to scroll.

Does that seem sensible? I know this is pushing the boundaries of what we expect people to use "Menu" for but I think it’s a case that should be handled for smaller screens anyway.

**Comment by makenosound** [comment]
I’ve have handled this in the consuming code by injecting a `max-height` container inside `<MenuContent>` but it’s a bit stinky (requires some layout jumping to handle the overflow gracefully). I _think_ nice behaviour here could be something like:

- Allow user to specify a `maxHeight` on the content and handle overflow with scrolling
- Handle moving above/below the reference element automatically
- Check the height fits within the space between the reference/page boundary fits the content and if it does not, reduce the `maxHeight` to ensure it does

What do you think, @sebpearce?

**Comment by sebpearce** [comment]
Sorry, just saw this! Yeah, allowing the user to set a `maxHeight` sounds good to me unless there's some way to do it gracefully automatically.

Another spanner in the works is that there is currently a design bug (yet to be acted on) that says the menu should be as wide as the content and not have a fixed width – which is impossible with the current structure since it uses absolute positioning – but it also means that any solution for the height would have to take this into account. In other words, if we can avoid relying on the fixed width or `position: absolute`, that'd be ideal.

This component was a port of 2 existing components so I'm almost as new to this as everyone else, but would be happy to pair on or review any modifications like this.

**Comment by makenosound** [comment]
> Sorry, just saw this!

All good! No rush on this stuff obvs. If it‘s urgent I’ll hassle y’all in Slack more aggressively :)

> Another spanner in the works is that there is currently a design bug (yet to be acted on) that says the menu should be as wide as the content and not have a fixed width

You mean the menu should be as wide as the content of the menu? Yeah, I am unsure if that is possible without applying some restrictions (for sanity).

* If the children of `<MenuContent>` have an explicit width, then `<MenuContent>` _can_ just wrap it without specifying a width.
* If the children of `<MenuContent>` _do not_ have an explicit width, then `<MenuContent>` would need to be able to impose a width to avoid the content potentially ending up very awkward.

I reckon we could tease those scenarios out with some more examples. Definitely happy to pair on it sometime!
