### ISSUE TITLE
What is a breaking change in Kaizen? 

### ISSUE THREAD

**Issue by ActuallyACat** [cultureamp/kaizen-design-system#675]
# About 
Developers should be aware of the definition of what a programmatic breaking change is [defined by Semantic Versioning](https://semver.org/), that is: 
```
Given a version number MAJOR.MINOR.PATCH, increment the:
    MAJOR version when you make incompatible API changes,
    MINOR version when you add functionality in a backwards compatible manner, and
    PATCH version when you make backwards compatible bug fixes.
```

This specification is not entirely descriptive of what is a breaking change in a Design System. We need to consider how visual changes to components cascade throughout the platform and be cognizant on the effect that has on components around it. Seemingly small changes can have a compounding effect on the platform and introduce visual defects. 

As an example, if we were to bump the padding of tab items from 1.125rem to 1.5rem, some consumers of tabs may experience text wrapping: 
1.125rem padding: 
![Screen Shot 2020-07-28 at 1 27 20 pm](https://user-images.githubusercontent.com/1621182/88616016-65ef9400-d0d6-11ea-8966-70360bb56278.png)

1.5rem padding: 
![Screen Shot 2020-07-28 at 1 29 05 pm](https://user-images.githubusercontent.com/1621182/88616011-6425d080-d0d6-11ea-93ca-3199b9d3260a.png)

I'd like to ask you all: 
## Resources
Visual Breaking Change in Design Systems - Nathan Curtis 
https://medium.com/eightshapes-llc/visual-breaking-change-in-design-systems-1e9109fac9c4

Versioning & Breaking Changes - Morningstar Design System 
https://designsystem.morningstar.com/getting-started/versioning-and-breaking-changes/

Versioning - Atlaskit 
https://atlaskit.atlassian.com/docs/guides/versioning

**Comment by ActuallyACat** [comment]
Some prior conversations DST had discussed internally


> What is major/breaking at CA? 
> Anything that could fail WCAG AA? 
> Rationale: Meeting our commitments to accessibility is important. Button or text colour changes could make text inaccessible.

> What is minor/feature at CA? 
> Changes that cause text to wrap, where it previously didn’t wrap (differing to MorningStar categorisation of “major”) - I think this was originally suggested by Michael.
> Rationale: Our support of l18n should mean the text of varying length already exist, and shouldn’t break in the platform.
>

**Comment by sebpearce** [comment]
Also probably worth pointing out that "what is a visual breaking change in Kaizen?" is a separate question from "should a visual breaking change be represented by a major version bump?".

My own opinion at the moment is that ideally, the meaning of semver would be left alone, because otherwise it would fail to be an accurate universal signifier and that is where all its value comes from (imagine a world where every company had their own "flavour" of semver!). If we could devise some sort of way of representing visual breaking changes as something parallel to semver I'd be all for it. Maybe it could be a check that happens on the PR and you can make commits in a certain format that will trigger it for the next person so that they look at it and discover information about the visual changes.

**Comment by mbylstra** [comment]
> "MAJOR version when you make incompatible API changes"
I don't even think this is helpful for _any_ codebase, let alone a design system. As an example, there was an update to an Elm library `OrdereredDict` that changed the behaviour of what happens when you insert an item with a key that already exists. The change in behaviour created a production bug, even though the API remained the same. The author of the library correctly and pragmaticaly (in my opinion) made it a breaking change even though the API had not changed. (The bug we had was because we didn't closely read and inspect code after doing a major upgrade, and we didn't have any tests). There's some question of whether the change in behaviour was worth it due to the risk of breaking consuming code, but that's a separate question).

So, I wonder if a MAJOR/breaking change could be anything that changes the behaviour of the codebase (regardless of whether the API has changed or not)

> If we could devise some sort of way of representing visual breaking changes as something parallel to semver I'd be all for it.
This is an interesting idea, but it seems like it would require a lot of tooling. Perhaps it's better to just veer on the side of breaking changes when there's a "significant" change. This would break the SemVer "standard", but I'm just not all that sure how useful SemVer's (slightly vague) specification really is in practice.  I think that conventional commits further muddies the waters, because "This convention dovetails with SemVer" (not clear what that means - does it conform to semver strictly or not, or is it an alternative to SemVer?) and it changes the language from MAJOR>BREAKING CHANGE, MINOR>FEAT, PATH>FIX (https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary) to add confusion. Are we even using the SemVer standard in Kaizen? Is that specified anywhere? Is this clear to everyone that contributes to Kaizen? It seems to me like we should just choose our own language come up with our own definitions and not worry about "standards" which seem ill-defined anyway.

**Comment by mbylstra** [comment]
BTW, @ActuallyACat thanks for kicking off this discussion! 💯

**Comment by mbylstra** [comment]
> It seems to me like we should just choose our own language
I mean, actually, we've already made a strong decision to use the Conventional Commits language (which I think was a good choice), it's more an issue of how we define what `fix`, `feat` and `BREAKING CHANGE` really means in Kaizen.

**Comment by mbylstra** [comment]
I remember @zioroboco made an internal post around `fix`, `feat` and `BREAKING CHANGE` being related to _impact_ rather than something very mechanical (and not necessarily that useful) like whether an API has changed, and I would love you to explain that better than my paraphrased version and whether you still hold that view.

**Comment by ActuallyACat** [comment]
> Also probably worth pointing out that "what is a visual breaking change in Kaizen?" is a separate question from "should a visual breaking change be represented by a major version bump?".

Heavy plus one. I wonder if I was too ambitious with combining these two questions in the single issue, or whether that latter should be its own follow-up issue 🤔 

>  If we could devise some sort of way of representing visual breaking changes as something parallel to semver I'd be all for it.
> It seems to me like we should just choose our own language come up with our own definitions and not worry about "standards" which seem ill-defined anyway.

I'm more interested in how we categorise the changes, rather than how to best enforce and represent them in changelogs (that sounds like a fun tooling and process challenge for later on!). What's the impact of text wrapping vs changing colours and failing WCAG contrast? Are these two things equivalent in terms of impact, or is one of them "worse"? What other examples of visual defects can we surface? 

One thing that gelled with me is Morningstar's definition of [breaking changes](https://designsystem.morningstar.com/getting-started/versioning-and-breaking-changes/?tab=major). It's very clear about how it categorises changes to styles, fonts, icons and API and what to expect from major/feat/fix.

**Comment by dlimiter** [comment]
The question of a breaking visual change is pretty broad and I'd be keen for opinions from other designers. In the context here of what I assume are intentional changes I'm thinking of things that would lead to parts of the UI looking or behaving like they are broken. The specifics could be any number of things like: 
- Visual misalignment/spacing 
- Typographic breakage (like wrapping in buttons, text overflow, hidden or compressed text etc.)
- Visual accessibility breakages(contrast, labelling etc.)
- Changes that break or confuse interaction (such as a container that overflows in a way that blocks an action)
