### ISSUE TITLE
modernise and refactor font fallbacks

### ISSUE THREAD

**Issue by mbylstra** [cultureamp/kaizen-design-system#829]
There is currently some inconsistency in our font fallbacks.

`kz-typography-xxxx` mixins  have  `"#{$kz-typography-xxx}, Helvetica, Arial, sans-serif"`, but `ca-type-inter` (although this is a legacy var) doesn't have any.

It feels like we could standardise and have tokens for font fallbacks.`Helvetica, Arial, sans-serif` seems outdated. The Apple system font is now "SF Pro" (I believe), so Apple products will default to Helvetica which could look quite ugly in 2020 depending on how sensitive you are to typography 😆 .  I think the current best practise is to just use `"Font Name", sans-serif`. In the past I think you need to add Arial and Helvetica because some browsers would default to a serif font even if you specified `sans-serif`. 

I think there should be a design token for fallback fonts, but I don't think there just just be _one_. Perhaps it should be heading style dependent. Maybe even it should be baked into every design token... wait... it is! (https://github.com/cultureamp/kaizen-design-system/blob/master/packages/design-tokens/tokens/typography.json#L5). I think that was added later. Still, my point on Helvetica stands!

Maybe we could get fancy and find the closest Apple system font to Greycliff for example (Avenir perhaps?), and then whatever the closest Microsoft font is (?) These are just some quick thoughts -  I think this could do with some research.

**Comment by mbylstra** [comment]
According to this site, http://www.identifont.com/find?similar=greycliff&q=Go, the closet Apple system font to Greycliff is San Francisco Display, which is better than Helvetica, and better again than "SF Pro Text" (the default body font I believe). It could be worth doing this, as I think it would make PDF renders potentially look way better (assuming we still have a PDF service that's unable to load the external fonts)

**Comment by ActuallyACat** [comment]
Just adding historical context / conversations to this issue. 

This has been discussed as the fallback in the internal DST chats and a few other places. 

--------------

"_We need the intended font family (Inter/Greycliff), Noto Sans as our fallback for any non-Latin characters e.g. CJK languages, then any installed or system fonts that would look sensible if the fonts are blocked or don't load for some reason. As a first cut:_"
```
"Greycliff", "Noto Sans", Helvetica, Arial, sans-serif;
"Inter", "Noto Sans", Helvetica, Arial, sans-serif;
```

--------------

Since it's relevant to this discussion, here's the Noto Sans exploration that @katsambarcus looked into:
![Noto Sans Exploration](https://user-images.githubusercontent.com/1621182/96950474-1d5d4080-1536-11eb-9fa8-066c86dfa78c.png)

--------------

There's also this PR here that adds those fallbacks to our design tokens:
https://github.com/cultureamp/kaizen-design-system/pull/558/files

This has yet to propogate through the whole system though, and as you have seen we still have plenty of variables kicking about with insufficient fallbacks.

**Comment by mbylstra** [comment]
Ah, I see, yes adding `"Noto Sans"` to the fallback is very important (much more important than any thing else mentioned in this issue). I glossed over that when I was looking at the tokens. Still, I think there's an opportunity to pick fallbacks to the right of `"Noto Sans"` that most closely resemble our fonts. I mean Helvetica and Arial look fine, but why specifically pick them when no OSes these days use them, and there are other system fonts in various systems that more closely resemble Inter and Greycliff? It's not a very high priority to get this right, but it's also low effort so _might as well_? My understanding of the new PDF service is that although it supports font loading, it's only use on specific pages and the old one (which doesn't support font loading) is still in wide use, so there's still a quick win to be had ther. I'm not sure of the performance impact of having many fallbacks defined, but I'd assume it's negligible - if a font doesn't exist in the system it just falls back to the next one in the chain.
